FROM node:latest as NODE_BUILD
WORKDIR /go/src/github.com/siyuan-note/siyuan/
ADD . /go/src/github.com/siyuan-note/siyuan/
RUN npm install --registry https://registry.npm.taobao.org -g pnpm 
RUN cd app && ELECTRON_MIRROR=https://cnpmjs.org/mirrors/electron/ pnpm install electron@26.2.3 -D
RUN cd app && pnpm --registry https://registry.npm.taobao.org install
RUN cd app && pnpm run build

FROM golang:alpine as GO_BUILD
WORKDIR /go/src/github.com/siyuan-note/siyuan/
COPY --from=NODE_BUILD /go/src/github.com/siyuan-note/siyuan/ /go/src/github.com/siyuan-note/siyuan/
ENV GO111MODULE=on
ENV CGO_ENABLED=1
ENV GOPROXY=https://goproxy.cn,direct
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories &&  \
    apk add --no-cache gcc musl-dev git
RUN cd kernel && go build --tags fts5 -v -ldflags "-s -w -X github.com/siyuan-note/siyuan/kernel/util.Mode=prod" && \
    mkdir /opt/siyuan/ && \
    mv /go/src/github.com/siyuan-note/siyuan/app/appearance/ /opt/siyuan/ && \
    mv /go/src/github.com/siyuan-note/siyuan/app/stage/ /opt/siyuan/ && \
    mv /go/src/github.com/siyuan-note/siyuan/app/guide/ /opt/siyuan/ && \
    mv /go/src/github.com/siyuan-note/siyuan/app/changelogs/ /opt/siyuan/ && \
    mv /go/src/github.com/siyuan-note/siyuan/kernel/kernel /opt/siyuan/ && \
    find /opt/siyuan/ -name .git | xargs rm -rf

FROM alpine:latest
LABEL org.opencontainers.image.source="https://github.com/Ran-snow/siyuan"
LABEL org.opencontainers.image.description="Some free change base on siyuan-note/siyuan"
LABEL org.opencontainers.image.licenses="AGPL-3.0"

WORKDIR /opt/siyuan/
COPY --from=GO_BUILD /opt/siyuan/ /opt/siyuan/
RUN addgroup --gid 1000 siyuan && \
    adduser --uid 1000 --ingroup siyuan --disabled-password siyuan && \
    apk add --no-cache ca-certificates tzdata && \
    cp -rf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    chown -R siyuan:siyuan /opt/siyuan/

ENV TZ=Asia/Shanghai
ENV RUN_IN_CONTAINER=true
EXPOSE 6806

USER siyuan
ENTRYPOINT ["/opt/siyuan/kernel"]

# docker buildx build --platform linux/amd64 -t test/siyuan:xxx .
# docker run --restart=always -d -v /home/siyuan:/opt/siyuan/workspace/ -p 80:6806 --name siyuan_001 test/siyuan:xxx --workspace=/opt/siyuan/workspace/

# git branch -v
# git pull siyuan master:siyuan
# git tag 2.10.13
# git push
# git push --tag

# git tag -d 2.10.13
# git push origin :refs/tags/2.10.13

# docker run \
#   --name siyuan_001 \
#   --restart=always \
#   -d \
#   -v /workspace:/siyuan/workspace \
#   -p 80:6806 \
#   ghcr.io/ran-snow/siyuan:2.12.2 \
#   --workspace=/siyuan/workspace

# addgroup --gid 1000 siyuan
# adduser --uid 1000 --ingroup siyuan --disabled-password siyuan
# mkdir /workspace
# chmod 777 -R /workspace
# chown -R siyuan:siyuan /workspace
# docker rm -f siyuan_001
# docker logs siyuan_001